openapi: "3.0.2"
info:
  title: Dummy API
  version: "1.0"
  description: "Dummy API description"
  license:
    name: MIT
    url: "https://dummyapi.example.com/LICENSE.md"
servers:
  - url: https://api.server.test/v1

components:
  schemas:
    Error:
      type: object
      required:
        - code
      properties:
        code:
          description: >
            A unique code that identifies the error.
            To view the error details see the link https://dev.cloudgaap.io/api/error-codes
          type: integer
          example: 404
        description:
          type: string
          description: >
            A human readable explanation specific to this occurrence of the
            problem that is helpful to locate the problem and give advice on how
            to proceed. Written in English and readable for engineers, usually not
            suited for non technical stakeholders and not localized.
          example: Resource not found
        details:
          type: string
          format: uri
          description: >
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://dev.cloudgaap.io/api/errors/constraint-violation'
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"

  responses:
    404NotFound:
      description: The resource does not exist.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    5xxErrorResponse:
      description: There were some error on the server side.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /dummy:
    get:
      operationId: dummyOp
      summary: "Dummy description"
      responses:
        "200":
          description: "Ok"
