openapi: "3.0.2"
info:
  title: Dummy API
  version: "1.0"
  description: "Dummy API description"
  license:
    name: MIT
    url: "https://dummyapi.example.com/LICENSE.md"
servers:
  - url: https://api.server.test/v1

components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: "Resource not found"
        errors:
          type: array
          example: []
          items:
            $ref: "#/components/schemas/Error"
    FiscalCodeType:
      description: The citizen's fiscal code.
      type: string
      pattern: "^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$"
      example: "SPNDNL80R13C555X"

  responses:
    400BadRequest:
      description: >
        The server cannot or will not process the request due to something that is perceived to be a client error
        (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    404NotFound:
      description: >
        The origin server did not find a current representation for the target resource or is not willing to disclose
        that one exists.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    5xxErrorResponse:
      description: There were some error on the server side.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

paths:
  /dummy:
    get:
      operationId: dummyOp
      summary: "Dummy description"
      responses:
        "200":
          description: "Ok"
